"use client";

import Link from "next/link";
import { useEffect, useRef, useState } from "react";
import { usePathname } from "next/navigation";
import { Bot, Loader2, MessageCircle, Send, X } from "lucide-react";
import { Button } from "@/components/ui/button";

type Message = { role: "user" | "assistant"; content: string; sources?: { title: string; href: string }[] };
const promptFor = (path: string) => path.includes("kasse") ? "Brauchen Sie Hilfe bei Lieferung oder Zahlung?" : path.includes("warenkorb") ? "Fragen zu Ihrem Warenkorb oder zur Lieferung?" : path.includes("produkt") || path.includes("kamin") ? "Soll ich Ihnen bei den Produktdetails helfen?" : "Wie kann ich Ihnen bei Produkten oder Lieferung helfen?";

export function FloatingChat({ name = "HolzDirekt Assistent" }: { name?: string }) {
  const path = usePathname(); const [open, setOpen] = useState(false); const [input, setInput] = useState(""); const [sending, setSending] = useState(false); const [messages, setMessages] = useState<Message[]>([]); const token = useRef("");
  useEffect(() => { token.current = window.localStorage.getItem("holzkraft:chat-token") || crypto.randomUUID(); window.localStorage.setItem("holzkraft:chat-token", token.current); const timer = window.setTimeout(() => { if (!sessionStorage.getItem(`holzkraft:chat-prompt:${path}`)) { setMessages([{ role: "assistant", content: promptFor(path) }]); sessionStorage.setItem(`holzkraft:chat-prompt:${path}`, "1"); } }, 5500); return () => clearTimeout(timer); }, [path]);
  const send = async () => { const message = input.trim(); if (!message || sending) return; setMessages((value) => [...value, { role: "user", content: message }]); setInput(""); setSending(true); try { const response = await fetch("/api/chat", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ sessionToken: token.current, message, path }) }); const data = await response.json() as { ok: boolean; answer?: string; sources?: { title: string; href: string }[]; message?: string }; setMessages((value) => [...value, { role: "assistant", content: data.answer ?? data.message ?? "Keine Antwort verfügbar.", sources: data.sources }]); } catch { setMessages((value) => [...value, { role: "assistant", content: "Der Assistent ist gerade nicht erreichbar." }]); } finally { setSending(false); } };
  return <div className="fixed bottom-5 right-5 z-50 print:hidden">{open ? <section aria-label="Chat mit dem digitalen Assistenten" className="mb-3 flex h-[min(560px,75vh)] w-[min(380px,calc(100vw-2.5rem))] flex-col overflow-hidden rounded-2xl border bg-background shadow-2xl"><header className="flex items-center justify-between bg-brand px-4 py-3 text-white"><div><p className="font-semibold">{name}</p><p className="text-xs text-white/70">KI-Assistent · Antworten aus freigegebenen Inhalten</p></div><Button size="icon" variant="ghost" className="text-white" onClick={() => setOpen(false)} aria-label="Chat schließen"><X className="size-4" /></Button></header><div className="flex-1 space-y-3 overflow-y-auto p-4" aria-live="polite">{messages.length === 0 ? <p className="text-muted text-sm">{promptFor(path)}</p> : messages.map((message, index) => <div key={index} className={`max-w-[88%] rounded-xl px-3 py-2 text-sm ${message.role === "user" ? "ml-auto bg-brand text-white" : "bg-elevated text-text"}`}><p>{message.content}</p>{message.sources?.length ? <div className="mt-2 space-y-1 border-t pt-2 text-xs">{message.sources.map((source) => <Link className="block underline" key={source.href + source.title} href={source.href}>{source.title}</Link>)}</div> : null}</div>)}{sending ? <Loader2 className="size-4 animate-spin" /> : null}</div><form className="flex gap-2 border-t p-3" onSubmit={(event) => { event.preventDefault(); void send(); }}><label className="sr-only" htmlFor="chat-message">Nachricht</label><input id="chat-message" className="min-w-0 flex-1 rounded-lg border px-3 text-sm" value={input} onChange={(event) => setInput(event.target.value)} maxLength={1200} placeholder="Ihre Frage…" /><Button size="icon" disabled={sending || input.trim().length < 2} aria-label="Nachricht senden"><Send className="size-4" /></Button></form></section> : messages.length ? <button onClick={() => setOpen(true)} className="mb-3 block max-w-64 rounded-xl border bg-background p-3 text-left text-sm shadow-lg"><span className="flex items-center gap-2 font-semibold"><Bot className="size-4" />Kann ich helfen?</span><span className="text-muted mt-1 block">{messages[0]?.content}</span></button> : null}<Button size="icon" className="size-14 rounded-full shadow-xl" onClick={() => setOpen((value) => !value)} aria-label={open ? "Chat schließen" : "Chat öffnen"}><MessageCircle className="size-6" /></Button></div>;
}
