import { NextResponse } from "next/server";
import { getMigrationAwareServiceSupabase } from "@/lib/db/server";
import { sendEmail } from "@/lib/notifications/email";
import { signRecovery } from "@/lib/cart/recovery";

const escape = (value: string) => value.replace(/[&<>"']/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[char]!);
export async function POST(request: Request) {
  if (!process.env.CRON_SECRET || request.headers.get("authorization") !== `Bearer ${process.env.CRON_SECRET}`) return NextResponse.json({ ok: false }, { status: 401 });
  const supabase = getMigrationAwareServiceSupabase(); const { data: settings } = await supabase.from("site_settings").select("cart_recovery_enabled,cart_recovery_second_delay_minutes,cart_recovery_max_reminders,company_name").eq("id", 1).maybeSingle(); if (!settings?.cart_recovery_enabled) return NextResponse.json({ ok: true, processed: 0 });
  const { data: carts } = await supabase.from("abandoned_carts").select("*").eq("status", "active").lte("next_reminder_at", new Date().toISOString()).lt("reminder_count", settings.cart_recovery_max_reminders).limit(50); let processed = 0;
  for (const cart of carts ?? []) { const token = signRecovery(cart.id); if (!token) continue; const idempotencyKey = `cart/${cart.id}/${cart.reminder_count + 1}`; const { data: job } = await supabase.from("notification_jobs").upsert({ kind: "abandoned_cart", idempotency_key: idempotencyKey, payload: { cart_id: cart.id }, status: "processing", attempts: 1, locked_at: new Date().toISOString() }, { onConflict: "idempotency_key" }).select("id,status").single(); if (!job || job.status === "sent") continue;
    const base = process.env.NEXT_PUBLIC_APP_URL || new URL(request.url).origin; const url = `${base}/warenkorb?recovery=${encodeURIComponent(token)}`; const items = Array.isArray(cart.items) ? cart.items as { name?: string; quantity?: number }[] : []; const result = await sendEmail({ to: cart.customer_email, subject: "Ihr Warenkorb wartet noch auf Sie", idempotencyKey, text: `Sie haben Artikel in Ihrem Warenkorb. Warenkorb fortsetzen: ${url}\nAbmelden: ${base}/api/warenkorb/unsubscribe?token=${encodeURIComponent(token)}`, html: `<h1>Ihr Warenkorb wartet noch</h1><p>Sie haben diese Erinnerung beim Checkout ausdrücklich aktiviert.</p><ul>${items.map((item) => `<li>${escape(String(item.quantity ?? 1))} × ${escape(String(item.name ?? "Artikel"))}</li>`).join("")}</ul><p><a href="${escape(url)}">Warenkorb fortsetzen</a></p><p><a href="${escape(`${base}/api/warenkorb/unsubscribe?token=${encodeURIComponent(token)}`)}">Keine weiteren Erinnerungen</a></p>` });
    if (result.sent) { const nextCount = cart.reminder_count + 1; const next = nextCount < settings.cart_recovery_max_reminders ? new Date(Date.now() + Number(settings.cart_recovery_second_delay_minutes) * 60_000).toISOString() : null; await supabase.from("abandoned_carts").update({ reminder_count: nextCount, next_reminder_at: next, status: next ? "active" : "expired" }).eq("id", cart.id); await supabase.from("notification_jobs").update({ status: "sent", provider_message_id: result.providerMessageId ?? null }).eq("id", job.id); processed++; } else { await supabase.from("notification_jobs").update({ status: "failed", last_error: result.error ?? result.skipped ?? "unknown", next_attempt_at: new Date(Date.now() + 15 * 60_000).toISOString() }).eq("id", job.id); }
  }
  return NextResponse.json({ ok: true, processed });
}
