import "server-only";
import { createHash } from "node:crypto";
import { getMigrationAwareServiceSupabase } from "@/lib/db/server";
import { generateInvoicePdf } from "./pdf";

export async function issueInvoiceForOrder(orderId: string) {
  const supabase = getMigrationAwareServiceSupabase(); const [{ data: order }, { data: items }, { data: settings }, { data: existing }] = await Promise.all([
    supabase.from("orders").select("*").eq("id", orderId).single(), supabase.from("order_items").select("*").eq("order_id", orderId).order("created_at"), supabase.from("site_settings").select("*").eq("id", 1).single(), supabase.from("invoices").select("id,invoice_number,status,document_path").eq("order_id", orderId).eq("kind", "invoice").neq("status", "void").maybeSingle(),
  ]);
  if (existing) throw new Error("Für diese Bestellung existiert bereits eine Rechnung."); if (!order || !items || !settings) throw new Error("Rechnungsdaten fehlen.");
  if (!settings.company_name || !settings.street || !settings.postal_code || !settings.city || (!settings.vat_id && !settings.tax_number)) throw new Error("Firmenanschrift sowie USt-IdNr. oder Steuernummer müssen vor Ausstellung gepflegt sein.");
  const issuedAt = new Date(); const due = new Date(issuedAt); due.setDate(due.getDate() + Number(settings.invoice_payment_terms_days ?? 14));
  const address = order.billing_address as Record<string, string>; const baseSnapshot = { issuedAt: issuedAt.toISOString(), issueDate: issuedAt.toLocaleDateString("de-DE"), dueDate: due.toLocaleDateString("de-DE"), orderNumber: order.order_number, company: { name: settings.company_name, legalForm: settings.legal_form, street: settings.street, postalCode: settings.postal_code, city: settings.city, countryCode: settings.country_code, vatId: settings.vat_id, taxNumber: settings.tax_number, commercialRegister: settings.commercial_register, registerCourt: settings.register_court, managingDirector: settings.managing_director, footer: settings.invoice_footer, logoUrl: settings.logo_url }, customer: { name: order.customer_name, email: order.customer_email, street: address.street, houseNumber: address.house_number, postcode: address.postcode, city: address.city }, items: items.map((item) => ({ name: item.name_snapshot, variant: item.variant_snapshot, quantity: item.quantity, unitPriceCents: item.unit_price_cents, discountCents: item.discount_cents ?? 0, lineTotalCents: item.line_total_cents, taxRate: item.tax_rate })), amounts: { subtotalCents: order.subtotal_cents, discountCents: order.discount_cents ?? 0, shippingCents: order.shipping_cents, taxCents: order.tax_cents, totalCents: order.total_cents }, promotionCode: order.promotion_code };
  const netCents = order.total_cents - order.tax_cents; const { data: draft, error } = await supabase.rpc("create_invoice_draft", { p_order_id: orderId, p_kind: "invoice", p_snapshot: baseSnapshot, p_net_cents: netCents, p_tax_cents: order.tax_cents, p_gross_cents: order.total_cents, p_due_date: due.toISOString().slice(0,10) }); if (error || !draft) throw new Error("Rechnungsnummer konnte nicht vergeben werden.");
  const invoice = Array.isArray(draft) ? draft[0] : draft; const snapshot = { ...baseSnapshot, invoiceNumber: invoice.invoice_number }; const bytes = await generateInvoicePdf(snapshot); const sha256 = createHash("sha256").update(bytes).digest("hex"); const path = `${issuedAt.getFullYear()}/${invoice.invoice_number}.pdf`; const { error: uploadError } = await supabase.storage.from("invoices").upload(path, bytes, { contentType: "application/pdf", upsert: false }); if (uploadError) throw new Error("Rechnungs-PDF konnte nicht gespeichert werden.");
  const { error: issueError } = await supabase.from("invoices").update({ status: "issued", snapshot, document_path: path, document_sha256: sha256, issued_at: issuedAt.toISOString() }).eq("id", invoice.id).eq("status", "draft"); if (issueError) throw new Error("Rechnung konnte nicht ausgestellt werden."); return { id: invoice.id as string, invoiceNumber: invoice.invoice_number as string };
}
